### ISSUE TITLE
Uncaught Error: Call to undefined function imagettfbbox

### ISSUE THREAD

**Issue by dignajar** [pytesNET/snicker#8]
Hi,
I just installed the plugin like a regular user :D just download, put the plugin in the folder and activate.

I have this error in the logs:
```
[Mon Apr  1 22:49:07 2019] PHP Fatal error:  Uncaught Error: Call to undefined function imagettfbbox() in /bludit/bl-plugins/snicker/includes/Gregwar/Captcha/CaptchaBuilder.php:323
Stack trace:
#0 /bludit/bl-plugins/snicker/includes/Gregwar/Captcha/CaptchaBuilder.php(437): Gregwar\Captcha\CaptchaBuilder->writePhrase(Resource id #176, 'ibnkc', '/Users/diego/gi...', 150, 40)
#1 /bludit/bl-plugins/snicker/system/class.snicker.php(125): Gregwar\Captcha\CaptchaBuilder->build(150, 40)
#2 /bludit/bl-plugins/snicker/themes/default/snicker.php(79): Snicker->generateCaptcha()
#3 /bludit/bl-plugins/snicker/system/class.snicker.php(251): Default_SnickerTemplate->form(Array, '', '', '')
#4 /bludit/bl-plugins/snicker/system/class.snicker.php(307): Snicker->renderTheme('form', Array, true)
#5 /bludit/bl-plugins/snicker/system/class.snicker.php(416): Snicker->renderForm()
#6 /bludit/bl-plugins/snicker/pl in /bludit/bl-plugins/snicker/includes/Gregwar/Captcha/CaptchaBuilder.php on line 323
[Mon Apr  1 22:49:07 2019] ::1:59023 [200]: /set-up-your-new-site - Uncaught Error: Call to undefined function imagettfbbox() in /bludit/bl-plugins/snicker/includes/Gregwar/Captcha/CaptchaBuilder.php:323
Stack trace:
#0 /bludit/bl-plugins/snicker/includes/Gregwar/Captcha/CaptchaBuilder.php(437): Gregwar\Captcha\CaptchaBuilder->writePhrase(Resource id #176, 'ibnkc', '/Users/diego/gi...', 150, 40)
#1 /bludit/bl-plugins/snicker/system/class.snicker.php(125): Gregwar\Captcha\CaptchaBuilder->build(150, 40)
#2 /bludit/bl-plugins/snicker/themes/default/snicker.php(79): Snicker->generateCaptcha()
#3 /bludit/bl-plugins/snicker/system/class.snicker.php(251): Default_SnickerTemplate->form(Array, '', '', '')
#4 /bludit/bl-plugins/snicker/system/class.snicker.php(307): Snicker->renderTheme('form', Array, true)
#5 /bludit/bl-plugins/snicker/system/class.snicker.php(416): Snicker->renderForm()
#6 /bludit/bl-plugins/snicker/pl in /bludit/bl-plugins/snicker/includes/Gregwar/Captcha/CaptchaBuilder.php on line 323
```

```
php --version
PHP 7.1.23 (cli) (built: Nov  7 2018 18:20:35) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by Joduai** [comment]
tbh I don't get that errors on php 7,2
Is this a specific php 7.1.x error?

**Comment by SamBrishes** [comment]
Hellow,

Cool, thanks for this issue ;D

The Captcha library (or better the [imagettfbbox](https://www.php.net/manual/en/function.imagettfbbox.php) function used by the library) requires the GD extension, and PHP needs to be compiled with the FreeType directive. Otherwise this function doesn't exist, so it doesn'T depends on the used PHP version.

I'll try to find a alternative library, which doesn't use TTF font files to be working.

Thanks, I guess the only solution for now is to just deactivate the Captcha.

Sincerely,
Sam

**Comment by SamBrishes** [comment]
Hellow, again,

the plugin now checks if GD is available and sets the default option to Gregwar (if it is available) or the new fallback library [PureCaptcha](https://github.com/OWASP/PureCaptcha). Of course you could also select one of both, but PureCaptcha should be avoided, because it is a bit harder to read. 

I guess it is really hard to create a clean Captcha image without the GD library. Maybe I find another solution, but this should work for the first time :D 

Sincerely,
Sam.

**Comment by dignajar** [comment]
For me I prefer use Google Catpcha.
I will try the new version tonight.
Thanks!

**Comment by SamBrishes** [comment]
Google reCaptcha is on my ToDo list, and should be available in the next update.

Thanks for testing!
